version: 2
updates:
  # GitHub Actions configurations
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.34.x-celestia"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge

  # Go package configurations
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge
